language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - python3 ./newsgen.py -d right.tdb -r right.txt pull
  - python3 -m nltk.downloader popular
  - python3 ./newsgen.py -d right.tdb -r right.txt article  
